// Quote-email delivery via Resend. The PDF is generated by the caller
// (routes/quotes.js → generateQuotePdf) and passed in as a Buffer; this
// module composes the branded HTML body and dispatches the message.
//
// Required env:
//   RESEND_API_KEY — re_xxxxxxx, from the Resend dashboard
//   EMAIL_FROM     — the verified-domain From address; defaults to
//                    admin@lyndhursthbc.com
//
// Throws if the API key is missing so the route can return 503.

import { Resend } from 'resend';

const FROM_DEFAULT = 'admin@lyndhursthbc.com';

function esc(s) {
  if (s == null) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

const CAD = new Intl.NumberFormat('en-CA', { style: 'currency', currency: 'CAD' });
function fmtMoney(v) {
  if (v == null) return '—';
  return CAD.format(Number(v));
}

function fmtDate(v) {
  if (!v) return '—';
  const d = new Date(v);
  if (Number.isNaN(d.getTime())) return '—';
  return d.toLocaleDateString('en-CA');
}

function renderHtml({ quote, customMessage }) {
  const customerLabel = quote.customer_name ? esc(quote.customer_name) : 'Valued Customer';
  const projectLabel = esc(quote.project_name || 'your project');
  const quoteNumber = esc(quote.quote_number);
  const today = fmtDate(quote.created_at);
  const validUntil = quote.valid_until ? fmtDate(quote.valid_until) : '30 days from issue';
  const grandTotal = fmtMoney(quote.total);
  const estimator = esc(quote.created_by || 'Lyndhurst Home Building Centre');

  // Custom message block — only rendered when non-empty.
  const messageBlock = (customMessage && customMessage.trim().length > 0) ? `
    <tr><td style="padding:0 0 16px 0;">
      <div style="background:#FFFBEC;border-left:3px solid #FFB800;padding:14px 16px;border-radius:4px;font-size:14px;color:#1A1A1A;line-height:1.55;white-space:pre-wrap;">${esc(customMessage)}</div>
    </td></tr>` : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Quote ${quoteNumber}</title>
</head>
<body style="margin:0;padding:0;background:#F5F5F5;font-family:-apple-system,'Segoe UI',Helvetica,Arial,sans-serif;color:#1A1A1A;">

<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#F5F5F5;padding:24px 0;">
  <tr><td align="center">

    <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;width:100%;background:#FFFFFF;border-radius:8px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,0.06);">

      <!-- Header -->
      <tr><td style="background:#0A0A0A;color:#FFFFFF;padding:24px;">
        <div style="font-size:18px;font-weight:700;letter-spacing:-0.2px;">Lyndhurst Home Building Centre</div>
        <div style="font-size:11px;color:#9CA3AF;margin-top:4px;">397 Lyndhurst Rd, Lyndhurst ON  K0E 1N0</div>
      </td></tr>

      <!-- Body -->
      <tr><td style="padding:32px 24px;">
        <table role="presentation" width="100%" cellpadding="0" cellspacing="0">

          <tr><td style="font-size:14px;color:#1A1A1A;padding:0 0 12px 0;">
            Dear ${customerLabel},
          </td></tr>
          <tr><td style="font-size:14px;color:#1A1A1A;padding:0 0 20px 0;line-height:1.55;">
            Please find attached your material estimate for ${projectLabel}.
          </td></tr>

          <!-- Estimate summary card -->
          <tr><td style="padding:0 0 20px 0;">
            <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:#F5F5F5;border-left:3px solid #CC0000;border-radius:4px;">
              <tr><td style="padding:14px 16px;">
                <table role="presentation" width="100%" cellpadding="0" cellspacing="0">
                  <tr>
                    <td style="font-size:9px;color:#6B7280;text-transform:uppercase;letter-spacing:0.5px;font-weight:600;padding:0 0 2px 0;">Quote</td>
                    <td style="font-size:9px;color:#6B7280;text-transform:uppercase;letter-spacing:0.5px;font-weight:600;padding:0 0 2px 0;">Quote date</td>
                  </tr>
                  <tr>
                    <td style="font-size:13px;color:#1A1A1A;padding:0 0 12px 0;">${quoteNumber}</td>
                    <td style="font-size:13px;color:#1A1A1A;padding:0 0 12px 0;">${esc(today)}</td>
                  </tr>
                  <tr>
                    <td style="font-size:9px;color:#6B7280;text-transform:uppercase;letter-spacing:0.5px;font-weight:600;padding:0 0 2px 0;">Valid until</td>
                    <td style="font-size:9px;color:#6B7280;text-transform:uppercase;letter-spacing:0.5px;font-weight:600;padding:0 0 2px 0;">Grand total</td>
                  </tr>
                  <tr>
                    <td style="font-size:13px;color:#1A1A1A;">${esc(validUntil)}</td>
                    <td style="font-size:16px;color:#CC0000;font-weight:700;">${grandTotal}</td>
                  </tr>
                </table>
              </td></tr>
            </table>
          </td></tr>

          ${messageBlock}

          <!-- Contact + signature -->
          <tr><td style="font-size:13px;color:#1A1A1A;line-height:1.55;padding:4px 0 8px 0;">
            If you have any questions about this estimate, please don't hesitate to reach out.
          </td></tr>
          <tr><td style="font-size:13px;color:#1A1A1A;line-height:1.6;padding:0 0 4px 0;">
            <strong>${estimator}</strong>
          </td></tr>
          <tr><td style="font-size:13px;color:#1A1A1A;line-height:1.6;padding:0 0 4px 0;">
            Phone: <a href="tel:6139282828" style="color:#CC0000;text-decoration:none;">613-928-2828</a>
          </td></tr>
          <tr><td style="font-size:13px;color:#1A1A1A;line-height:1.6;padding:0 0 4px 0;">
            Email: <a href="mailto:admin@lyndhursthbc.com" style="color:#CC0000;text-decoration:none;">admin@lyndhursthbc.com</a>
          </td></tr>

        </table>
      </td></tr>

      <!-- Footer -->
      <tr><td style="padding:18px 24px;border-top:1px solid #E0E0E0;background:#FAFAFA;">
        <div style="font-size:10px;color:#6B7280;line-height:1.5;text-align:center;">
          This estimate is valid for 30 days. Prices subject to change without notice.
        </div>
        <div style="font-size:10px;color:#9CA3AF;text-align:center;margin-top:6px;">
          Powered by BuildTek | <a href="https://buildtek.org" style="color:#9CA3AF;text-decoration:none;">buildtek.org</a>
        </div>
      </td></tr>

    </table>

  </td></tr>
</table>

</body>
</html>`;
}

export async function sendQuoteEmail({ quote, recipientEmail, customMessage, pdfBuffer }) {
  if (!process.env.RESEND_API_KEY) {
    const err = new Error('Email service not configured');
    err.code = 'EMAIL_NOT_CONFIGURED';
    throw err;
  }
  const resend = new Resend(process.env.RESEND_API_KEY);
  const from = process.env.EMAIL_FROM || FROM_DEFAULT;

  const subject = `Quote #${quote.quote_number} — ${quote.project_name || 'Project'} | Lyndhurst Home Building Centre`;
  const html = renderHtml({ quote, customMessage });

  const { data, error } = await resend.emails.send({
    from,
    to: recipientEmail,
    subject,
    html,
    attachments: pdfBuffer
      ? [{ filename: `Quote-${quote.quote_number}.pdf`, content: pdfBuffer }]
      : [],
  });
  if (error) {
    const e = new Error(error.message || 'Resend send failed');
    e.code = 'RESEND_ERROR';
    throw e;
  }
  return data;
}
